version: '3.9'

services:

  fsm_bot:
        container_name: FsmBot
        image: fsm_bot

        build: .

        environment:
            - DEBUG=1

        volumes:
         - "/fsm_bot_data"

        # restart: on-failure

volumes:
  logs:
