version: '3.9'

services:
  redis:
    image: redis:alpine
    command: redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - 6379:6379
  db:
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
        - 5434:5432
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
  fsm_bot:
        container_name: FsmBot
        image: fsm_bot
        build: .
        environment:
            - BOT_TOKEN=${BOT_TOKEN}
            - DEBUG=1

        volumes:
         - "/fsm_bot_data"

        restart: always
        depends_on:
          - redis
          - db

volumes:
  pgdata:
  logs:
